config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :milkshakes do
    resources :doses, only: [:create, :new]
  end
  resources :doses, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :ingredient
  belongs_to :milkshake
end

app/models/favourite.rb
class Favourite < ApplicationRecord
  belongs_to :user
  belongs_to :milkshakes
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  has_many :milkshakes, through: :doses
  validates :name, presence: true, uniqueness: true
end

app/models/milkshake.rb
class Milkshake < ApplicationRecord
  belongs_to :user
  has_many :favourites
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  has_one_attached :photo
  validates :name, presence: true, uniqueness: true
  validates :description, presence: true
  validates :photo, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :milkshakes
  has_many :ingredients
  has_many :favourites
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  before_action :find_milkshake, only: [:new, :create]
  def new
    @dose = Dose.new
    @dose.milkshake = @milkshake
    authorize @dose
  end

  def create
    @dose = Dose.new(dose_params)
    @dose.milkshake = @milkshake
    authorize @dose
    if @dose.save
      redirect_to milkshake_path(@milkshake)
    else
      render :new
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    authorize @dose
    @milkshake = @dose.milkshake
    @dose.destroy
    redirect_to milkshake_path(@milkshake)
  end
  
  private

  def dose_params
    params.require(:dose).permit(:name, :ingredient_id, :milkshake_id)
  end

  def find_milkshake
    @milkshake = Milkshake.find(params[:milkshake_id])
  end
end

app/controllers/favourites_controller.rb
class FavouritesController < ApplicationController
end

app/controllers/milkshakes_controller.rb
class MilkshakesController < ApplicationController
  before_action :find_index, only: %i[show edit update destroy]
  def index
    @milkshakes = policy_scope(Milkshake).order(created_at: :desc)
  end

  def show
    @dose = Dose.new
    authorize @milkshake
  end

  def new
    @milkshake = Milkshake.new
    authorize @milkshake
  end

  def create
    @milkshake = Milkshake.new(milkshake_params)
    authorize @milkshake
    @milkshake.user = current_user
    if @milkshake.save
      redirect_to milkshake_path(@milkshake)
    else
      render :new
    end
  end

  def edit
    authorize @milkshake
  end

  def update
    authorize @milkshake
    @milkshake.update(milkshake_params)
    redirect_to milkshake_path(@milkshake)
  end

  def destroy
    authorize @milkshake
    @milkshake.destroy
    redirect_to milkshakes_path
  end

  private 
  
  def find_index
    @milkshake = Milkshake.find(params[:id])
  end

  def milkshake_params
    params.require(:milkshake).permit(:name, :description, :photo)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/doses/new.html.erb
<div class="container">
  <%= simple_form_for [ @milkshake, @dose] do |f| %>
    <%= f.input :name %>
    <%= f.association :ingredient %>
    <%= f.submit "Submit Ingredient", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMyNewMilkshakesPage</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/milkshakes/edit.html.erb
<h1>Milkshakes#edit</h1>
<p>Find me in app/views/milkshakes/edit.html.erb</p>

app/views/milkshakes/index.html.erb
<div class="container">
  <h1>Welcome</h1>
  <div class="cards">
    <% @milkshakes.each do |milkshake| %>
    <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path milkshake.photo.key, crop: :fill %>')">
      <%= link_to milkshake.name, milkshake_path(milkshake) %>
    </div>
    <% end %>
  </div>
</div>


  

app/views/milkshakes/new.html.erb
<div class="container">
<h1>Make new Milkshake</h1>
  <%= simple_form_for @milkshake do |f| %>
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :photo, as: :file %>
    <%= f.submit "Submit milkshake", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/milkshakes/show.html.erb
<div class="container">
  <div class="card-product">
    <%= cl_image_tag @milkshake.photo.key, crop: :fill %>
    <div class="card-product-infos">
      <h2><%= @milkshake.name %></h2>
      <p><%= @milkshake.description %></p>
      <ul>
        <% @milkshake.doses.each do |dose| %>
          <li>
            <%= dose.ingredient.name %> --- <%= dose.name %>
              <% if policy(@milkshake).update? %>
                <%= link_to "X",
                  dose_path(dose),
                  method: :delete,
                  data: { confirm: "Are you sure?" } %>
              <% end %>
          </li>
        <% end %>
      <ul>
      <% if policy(@milkshake).update? %>
        <%= link_to "Add Dose", new_milkshake_dose_path(@milkshake), class: "btn btn-primary" %>
      <% end %>
    </div>
    <div>
      <% if policy(@milkshake).update? %>
        <%= link_to "Edit", edit_milkshake_path(@milkshake), class: "btn btn-success" %>
        <%= link_to 'Delete', milkshake_path(@milkshake),class: "btn btn-danger", method: :delete,
        data: { confirm: "Are you sure?" } %>
      <% end %>
    </div>
  </div> 
</div>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-text">
    This website was <i class="fas fa-laptop-code"></i> by <a href="https://github.com/beno5">Benjamin</a>.
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>
    <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Milkshakes", milkshakes_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <% if policy(Milkshake).create? %>
            <%= link_to "New Milkshake", new_milkshake_path, class: "nav-link" %>
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to "Favourites", milkshakes_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "About me", milkshakes_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>